# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help410', '0002_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('HC', 'House Cleaning'), ('LD', 'Laundry'), ('PD', 'Pick up & Delivery'), ('GC', 'Grocery'), ('CK', 'Cooking'), ('CW', 'Car Wash')], max_length=2),
        ),
        migrations.AlterField(
            model_name='gig',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
